export const signupContants = {
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',

    GET_ORIGIN_REQUEST: 'GET_ORIGIN_REQUEST',
    GET_ORIGIN_SUCCESS: 'GET_ORIGIN_SUCCESS',
    GET_ORIGIN_FAILURE: 'GET_ORIGIN_FAILURE',

    GET_REGIONS_REQUEST: 'GET_REGIONS_REQUEST',
    GET_REGIONS_SUCCESS: 'GET_REGIONS_SUCCESS',
    GET_REGIONS_FAILURE: 'GET_REGIONS_FAILURE',

    GET_CITIES_BY_REGION_REQUEST: 'GET_CITIES_BY_REGION_REQUEST',
    GET_CITIES_BY_REGION_SUCCESS: 'GET_CITIES_BY_REGION_SUCCESS',
    GET_CITIES_BY_REGION_FAILURE: 'GET_CITIES_BY_REGION_FAILURE',
};
