export const signupContants = {

    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',

    GET_ORIGIN_REQUEST: 'GET_ORIGIN_REQUEST',
    GET_ORIGIN_SUCCESS: 'GET_ORIGIN_SUCCESS',
    GET_ORIGIN_FAILURE: 'GET_ORIGIN_FAILURE',
}